2025-04-11 11:18:14 | INFO | openai_api_server | args: Namespace(host='localhost', port=8000, controller_address='http://localhost:21001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2025-04-11 11:18:14 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m9508[0m]
2025-04-11 11:18:14 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2025-04-11 11:18:14 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2025-04-11 11:18:14 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
2025-04-11 11:18:18 | INFO | stdout | [32mINFO[0m:     ::1:52517 - "[1mGET / HTTP/1.1[0m" [31m404 Not Found[0m
2025-04-11 11:18:18 | INFO | stdout | [32mINFO[0m:     ::1:52517 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m
2025-04-11 11:18:21 | INFO | stdout | [32mINFO[0m:     ::1:52517 - "[1mGET /docs HTTP/1.1[0m" [32m200 OK[0m
2025-04-11 11:18:22 | INFO | stdout | [32mINFO[0m:     ::1:52517 - "[1mGET /openapi.json HTTP/1.1[0m" [32m200 OK[0m
2025-04-11 11:18:30 | INFO | stdout | [32mINFO[0m:     ::1:52518 - "[1mGET /v1/models HTTP/1.1[0m" [32m200 OK[0m
2025-04-11 11:22:45 | INFO | stdout | [32mINFO[0m:     ::1:52690 - "[1mGET /docs HTTP/1.1[0m" [32m200 OK[0m
2025-04-11 11:22:45 | INFO | stdout | [32mINFO[0m:     ::1:52690 - "[1mGET /openapi.json HTTP/1.1[0m" [32m200 OK[0m
2025-04-11 11:23:41 | ERROR | stderr | D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py:136: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
2025-04-11 11:23:41 | ERROR | stderr |   ErrorResponse(message=message, code=code).dict(), status_code=400
2025-04-11 11:23:41 | INFO | stdout | [32mINFO[0m:     127.0.0.1:52838 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2025-04-11 12:52:08 | INFO | stdout | [32mINFO[0m:     ::1:58503 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2025-04-11 12:52:51 | INFO | stdout | [32mINFO[0m:     ::1:58629 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2025-04-11 12:53:30 | INFO | stdout | [32mINFO[0m:     ::1:58843 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 12:53:30 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 12:53:30 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 12:53:30 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     raise exc
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 12:53:30 | ERROR | stderr |     raise exc
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 12:53:30 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 12:53:30 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 12:53:30 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 12:53:30 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 12:53:30 | ERROR | stderr |     raise exc
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 12:53:30 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 12:53:30 | ERROR | stderr |     response = await f(request)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 12:53:30 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 12:53:30 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 12:53:30 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 12:53:30 | ERROR | stderr |     name=conv["name"],
2025-04-11 12:53:30 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 12:53:30 | INFO | stdout | [32mINFO[0m:     ::1:58847 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 12:53:30 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 12:53:30 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 12:53:30 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     raise exc
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 12:53:30 | ERROR | stderr |     raise exc
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 12:53:30 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 12:53:30 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 12:53:30 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 12:53:30 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 12:53:30 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 12:53:30 | ERROR | stderr |     raise exc
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 12:53:30 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 12:53:30 | ERROR | stderr |     response = await f(request)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 12:53:30 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 12:53:30 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 12:53:30 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 12:53:30 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 12:53:30 | ERROR | stderr |     name=conv["name"],
2025-04-11 12:53:30 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 12:53:31 | INFO | stdout | [32mINFO[0m:     ::1:58850 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 12:53:31 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 12:53:31 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 12:53:31 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 12:53:31 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 12:53:31 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 12:53:31 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 12:53:31 | ERROR | stderr |     raise exc
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 12:53:31 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 12:53:31 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 12:53:31 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 12:53:31 | ERROR | stderr |     raise exc
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 12:53:31 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 12:53:31 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 12:53:31 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 12:53:31 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 12:53:31 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 12:53:31 | ERROR | stderr |     raise exc
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 12:53:31 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 12:53:31 | ERROR | stderr |     response = await f(request)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 12:53:31 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 12:53:31 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 12:53:31 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 12:53:31 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 12:53:31 | ERROR | stderr |     name=conv["name"],
2025-04-11 12:53:31 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 12:55:41 | INFO | stdout | [32mINFO[0m:     ::1:59232 - "[1mGET /v1/models HTTP/1.1[0m" [32m200 OK[0m
2025-04-11 13:01:45 | INFO | stdout | [32mINFO[0m:     ::1:59642 - "[1mGET /v1/models HTTP/1.1[0m" [32m200 OK[0m
2025-04-11 13:03:26 | INFO | stdout | [32mINFO[0m:     127.0.0.1:59803 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 13:03:26 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 13:03:26 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 13:03:26 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 13:03:26 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 13:03:26 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 13:03:26 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 13:03:26 | ERROR | stderr |     raise exc
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 13:03:26 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 13:03:26 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 13:03:26 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 13:03:26 | ERROR | stderr |     raise exc
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 13:03:26 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 13:03:26 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 13:03:26 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 13:03:26 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 13:03:26 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 13:03:26 | ERROR | stderr |     raise exc
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 13:03:26 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 13:03:26 | ERROR | stderr |     response = await f(request)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 13:03:26 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 13:03:26 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 13:03:26 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 13:03:26 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 13:03:26 | ERROR | stderr |     name=conv["name"],
2025-04-11 13:03:26 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 13:03:27 | INFO | stdout | [32mINFO[0m:     127.0.0.1:59807 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 13:03:27 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 13:03:27 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 13:03:27 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 13:03:27 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 13:03:27 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 13:03:27 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 13:03:27 | ERROR | stderr |     raise exc
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 13:03:27 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 13:03:27 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 13:03:27 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 13:03:27 | ERROR | stderr |     raise exc
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 13:03:27 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 13:03:27 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 13:03:27 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 13:03:27 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 13:03:27 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 13:03:27 | ERROR | stderr |     raise exc
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 13:03:27 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 13:03:27 | ERROR | stderr |     response = await f(request)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 13:03:27 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 13:03:27 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 13:03:27 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 13:03:27 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 13:03:27 | ERROR | stderr |     name=conv["name"],
2025-04-11 13:03:27 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 13:03:28 | INFO | stdout | [32mINFO[0m:     127.0.0.1:59811 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 13:03:28 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 13:03:28 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 13:03:28 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 13:03:28 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 13:03:28 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 13:03:28 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 13:03:28 | ERROR | stderr |     raise exc
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 13:03:28 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 13:03:28 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 13:03:28 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 13:03:28 | ERROR | stderr |     raise exc
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 13:03:28 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 13:03:28 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 13:03:28 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 13:03:28 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 13:03:28 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 13:03:28 | ERROR | stderr |     raise exc
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 13:03:28 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 13:03:28 | ERROR | stderr |     response = await f(request)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 13:03:28 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 13:03:28 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 13:03:28 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 13:03:28 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 13:03:28 | ERROR | stderr |     name=conv["name"],
2025-04-11 13:03:28 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 14:10:52 | INFO | stdout | [32mINFO[0m:     127.0.0.1:52169 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2025-04-11 14:13:45 | ERROR | stderr | [32mINFO[0m:     Shutting down
2025-04-11 14:13:45 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2025-04-11 14:13:45 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2025-04-11 14:13:45 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m9508[0m]
2025-04-11 14:13:51 | INFO | openai_api_server | args: Namespace(host='localhost', port=8000, controller_address='http://localhost:21001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2025-04-11 14:13:51 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m9264[0m]
2025-04-11 14:13:51 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2025-04-11 14:13:51 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2025-04-11 14:13:51 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
2025-04-11 14:49:26 | ERROR | stderr | D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py:136: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
2025-04-11 14:49:26 | ERROR | stderr |   ErrorResponse(message=message, code=code).dict(), status_code=400
2025-04-11 14:49:26 | INFO | stdout | [32mINFO[0m:     127.0.0.1:55424 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2025-04-11 15:19:58 | INFO | stdout | [32mINFO[0m:     ::1:57659 - "[1mGET /v1/models HTTP/1.1[0m" [32m200 OK[0m
2025-04-11 15:20:05 | INFO | stdout | [32mINFO[0m:     ::1:57666 - "[1mGET /v1/models HTTP/1.1[0m" [32m200 OK[0m
2025-04-11 15:48:48 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60134 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:48:48 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:48:48 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:48:48 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:48:48 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:48:48 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:48:48 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:48:48 | ERROR | stderr |     raise exc
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:48:48 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:48:48 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:48:48 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:48:48 | ERROR | stderr |     raise exc
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:48:48 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:48:48 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:48:48 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:48:48 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:48:48 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:48:48 | ERROR | stderr |     raise exc
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:48:48 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:48:48 | ERROR | stderr |     response = await f(request)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:48:48 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:48:48 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:48:48 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:48:48 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:48:48 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:48:48 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:48:49 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60151 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:48:49 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:48:49 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:48:49 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:48:49 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:48:49 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:48:49 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:48:49 | ERROR | stderr |     raise exc
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:48:49 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:48:49 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:48:49 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:48:49 | ERROR | stderr |     raise exc
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:48:49 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:48:49 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:48:49 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:48:49 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:48:49 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:48:49 | ERROR | stderr |     raise exc
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:48:49 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:48:49 | ERROR | stderr |     response = await f(request)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:48:49 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:48:49 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:48:49 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:48:49 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:48:49 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:48:49 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:48:50 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60155 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:48:50 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:48:50 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:48:50 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:48:50 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:48:50 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:48:50 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:48:50 | ERROR | stderr |     raise exc
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:48:50 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:48:50 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:48:50 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:48:50 | ERROR | stderr |     raise exc
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:48:50 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:48:50 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:48:50 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:48:50 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:48:50 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:48:50 | ERROR | stderr |     raise exc
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:48:50 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:48:50 | ERROR | stderr |     response = await f(request)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:48:50 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:48:50 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:48:50 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:48:50 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:48:50 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:48:50 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:49:12 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60172 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:49:12 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:49:12 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:49:12 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:49:12 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:49:12 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:49:12 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:49:12 | ERROR | stderr |     raise exc
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:49:12 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:49:12 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:49:12 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:49:12 | ERROR | stderr |     raise exc
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:49:12 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:49:12 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:49:12 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:49:12 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:49:12 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:49:12 | ERROR | stderr |     raise exc
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:49:12 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:49:12 | ERROR | stderr |     response = await f(request)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:49:12 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:49:12 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:49:12 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:49:12 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:49:12 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:49:12 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:49:13 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60177 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:49:13 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:49:13 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:49:13 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:49:13 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:49:13 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:49:13 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:49:13 | ERROR | stderr |     raise exc
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:49:13 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:49:13 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:49:13 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:49:13 | ERROR | stderr |     raise exc
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:49:13 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:49:13 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:49:13 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:49:13 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:49:13 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:49:13 | ERROR | stderr |     raise exc
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:49:13 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:49:13 | ERROR | stderr |     response = await f(request)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:49:13 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:49:13 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:49:13 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:49:13 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:49:13 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:49:13 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:49:14 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60191 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:49:14 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:49:14 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:49:14 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:49:14 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:49:14 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:49:14 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:49:14 | ERROR | stderr |     raise exc
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:49:14 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:49:14 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:49:14 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:49:14 | ERROR | stderr |     raise exc
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:49:14 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:49:14 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:49:14 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:49:14 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:49:14 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:49:14 | ERROR | stderr |     raise exc
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:49:14 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:49:14 | ERROR | stderr |     response = await f(request)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:49:14 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:49:14 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:49:14 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:49:14 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:49:14 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:49:14 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:50:51 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60260 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:50:51 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:50:51 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:50:51 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:50:51 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:50:51 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:50:51 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:50:51 | ERROR | stderr |     raise exc
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:50:51 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:50:51 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:50:51 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:50:51 | ERROR | stderr |     raise exc
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:50:51 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:50:51 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:50:51 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:50:51 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:50:51 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:50:51 | ERROR | stderr |     raise exc
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:50:51 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:50:51 | ERROR | stderr |     response = await f(request)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:50:51 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:50:51 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:50:51 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:50:51 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:50:51 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:50:51 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:50:52 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60264 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:50:52 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:50:52 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:50:52 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:50:52 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:50:52 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:50:52 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:50:52 | ERROR | stderr |     raise exc
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:50:52 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:50:52 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:50:52 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:50:52 | ERROR | stderr |     raise exc
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:50:52 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:50:52 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:50:52 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:50:52 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:50:52 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:50:52 | ERROR | stderr |     raise exc
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:50:52 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:50:52 | ERROR | stderr |     response = await f(request)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:50:52 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:50:52 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:50:52 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:50:52 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:50:52 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:50:52 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:50:53 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60269 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:50:53 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:50:53 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:50:53 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:50:53 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:50:53 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:50:53 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:50:53 | ERROR | stderr |     raise exc
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:50:53 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:50:53 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:50:53 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:50:53 | ERROR | stderr |     raise exc
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:50:53 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:50:53 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:50:53 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:50:53 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:50:53 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:50:53 | ERROR | stderr |     raise exc
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:50:53 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:50:53 | ERROR | stderr |     response = await f(request)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:50:53 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:50:53 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:50:53 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:50:53 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:50:53 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:50:53 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:52:15 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60319 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [31m400 Bad Request[0m
2025-04-11 15:53:05 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60347 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:53:05 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:53:05 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:53:05 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     raise exc
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:53:05 | ERROR | stderr |     raise exc
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:53:05 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:53:05 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:53:05 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:53:05 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:53:05 | ERROR | stderr |     raise exc
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:53:05 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:53:05 | ERROR | stderr |     response = await f(request)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:53:05 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:53:05 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:53:05 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:53:05 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:53:05 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:53:05 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60351 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:53:05 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:53:05 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:53:05 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     raise exc
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:53:05 | ERROR | stderr |     raise exc
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:53:05 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:53:05 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:53:05 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:53:05 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:53:05 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:53:05 | ERROR | stderr |     raise exc
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:53:05 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:53:05 | ERROR | stderr |     response = await f(request)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:53:05 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:53:05 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:53:05 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:53:05 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:53:05 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:53:05 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:53:06 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60355 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:53:06 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:53:06 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:53:06 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:53:06 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:53:06 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:53:06 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:53:06 | ERROR | stderr |     raise exc
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:53:06 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:53:06 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:53:06 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:53:06 | ERROR | stderr |     raise exc
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:53:06 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:53:06 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:53:06 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:53:06 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:53:06 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:53:06 | ERROR | stderr |     raise exc
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:53:06 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:53:06 | ERROR | stderr |     response = await f(request)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:53:06 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:53:06 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:53:06 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:53:06 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:53:06 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:53:06 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:57:16 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60674 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:57:16 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:57:16 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:57:16 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     raise exc
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:57:16 | ERROR | stderr |     raise exc
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:57:16 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:57:16 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:57:16 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:57:16 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:57:16 | ERROR | stderr |     raise exc
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:57:16 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:57:16 | ERROR | stderr |     response = await f(request)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:57:16 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:57:16 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:57:16 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:57:16 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:57:16 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:57:16 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60678 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:57:16 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:57:16 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:57:16 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     raise exc
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:57:16 | ERROR | stderr |     raise exc
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:57:16 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:57:16 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:57:16 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:57:16 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:57:16 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:57:16 | ERROR | stderr |     raise exc
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:57:16 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:57:16 | ERROR | stderr |     response = await f(request)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:57:16 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:57:16 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:57:16 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:57:16 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:57:16 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:57:16 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 15:57:17 | INFO | stdout | [32mINFO[0m:     127.0.0.1:60682 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 15:57:17 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 15:57:17 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 15:57:17 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 15:57:17 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 15:57:17 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 15:57:17 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 15:57:17 | ERROR | stderr |     raise exc
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 15:57:17 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 15:57:17 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 15:57:17 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:57:17 | ERROR | stderr |     raise exc
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:57:17 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 15:57:17 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 15:57:17 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 15:57:17 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 15:57:17 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 15:57:17 | ERROR | stderr |     raise exc
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 15:57:17 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 15:57:17 | ERROR | stderr |     response = await f(request)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 15:57:17 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 15:57:17 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 15:57:17 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 15:57:17 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 15:57:17 | ERROR | stderr |     name=conv["name"],
2025-04-11 15:57:17 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 16:26:28 | ERROR | stderr | [32mINFO[0m:     Shutting down
2025-04-11 16:26:28 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2025-04-11 16:26:28 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2025-04-11 16:26:28 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m9264[0m]
2025-04-11 20:45:31 | INFO | openai_api_server | args: Namespace(host='localhost', port=8000, controller_address='http://localhost:21001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2025-04-11 20:45:31 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m18108[0m]
2025-04-11 20:45:31 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2025-04-11 20:45:31 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2025-04-11 20:45:31 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
2025-04-11 20:46:20 | INFO | stdout | [32mINFO[0m:     127.0.0.1:64057 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 20:46:20 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 20:46:20 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 20:46:20 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     raise exc
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 20:46:20 | ERROR | stderr |     raise exc
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 20:46:20 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 20:46:20 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 20:46:20 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 20:46:20 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 20:46:20 | ERROR | stderr |     raise exc
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 20:46:20 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 20:46:20 | ERROR | stderr |     response = await f(request)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 20:46:20 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 20:46:20 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 20:46:20 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 20:46:20 | ERROR | stderr |     name=conv["name"],
2025-04-11 20:46:20 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 20:46:20 | INFO | stdout | [32mINFO[0m:     127.0.0.1:64062 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 20:46:20 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 20:46:20 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 20:46:20 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     raise exc
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 20:46:20 | ERROR | stderr |     raise exc
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 20:46:20 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 20:46:20 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 20:46:20 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 20:46:20 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 20:46:20 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 20:46:20 | ERROR | stderr |     raise exc
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 20:46:20 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 20:46:20 | ERROR | stderr |     response = await f(request)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 20:46:20 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 20:46:20 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 20:46:20 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 20:46:20 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 20:46:20 | ERROR | stderr |     name=conv["name"],
2025-04-11 20:46:20 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 20:46:21 | INFO | stdout | [32mINFO[0m:     127.0.0.1:64066 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [91m500 Internal Server Error[0m
2025-04-11 20:46:21 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2025-04-11 20:46:21 | ERROR | stderr | Traceback (most recent call last):
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
2025-04-11 20:46:21 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
2025-04-11 20:46:21 | ERROR | stderr |     return await self.app(scope, receive, send)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\applications.py", line 1054, in __call__
2025-04-11 20:46:21 | ERROR | stderr |     await super().__call__(scope, receive, send)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\applications.py", line 112, in __call__
2025-04-11 20:46:21 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
2025-04-11 20:46:21 | ERROR | stderr |     raise exc
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
2025-04-11 20:46:21 | ERROR | stderr |     await self.app(scope, receive, _send)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
2025-04-11 20:46:21 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
2025-04-11 20:46:21 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 20:46:21 | ERROR | stderr |     raise exc
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 20:46:21 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 714, in __call__
2025-04-11 20:46:21 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 734, in app
2025-04-11 20:46:21 | ERROR | stderr |     await route.handle(scope, receive, send)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 288, in handle
2025-04-11 20:46:21 | ERROR | stderr |     await self.app(scope, receive, send)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 76, in app
2025-04-11 20:46:21 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
2025-04-11 20:46:21 | ERROR | stderr |     raise exc
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
2025-04-11 20:46:21 | ERROR | stderr |     await app(scope, receive, sender)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\starlette\routing.py", line 73, in app
2025-04-11 20:46:21 | ERROR | stderr |     response = await f(request)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 301, in app
2025-04-11 20:46:21 | ERROR | stderr |     raw_response = await run_endpoint_function(
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
2025-04-11 20:46:21 | ERROR | stderr |     return await dependant.call(**values)
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 424, in create_chat_completion
2025-04-11 20:46:21 | ERROR | stderr |     gen_params = await get_gen_params(
2025-04-11 20:46:21 | ERROR | stderr |   File "D:\python_workspace\zj_venv\fufan-chat-api\lib\site-packages\fastchat\serve\openai_api_server.py", line 288, in get_gen_params
2025-04-11 20:46:21 | ERROR | stderr |     name=conv["name"],
2025-04-11 20:46:21 | ERROR | stderr | TypeError: string indices must be integers
2025-04-11 20:47:34 | INFO | stdout | [32mINFO[0m:     127.0.0.1:64113 - "[1mGET /docs HTTP/1.1[0m" [32m200 OK[0m
2025-04-11 20:47:35 | INFO | stdout | [32mINFO[0m:     127.0.0.1:64113 - "[1mGET /openapi.json HTTP/1.1[0m" [32m200 OK[0m
2025-04-11 20:47:38 | INFO | stdout | [32mINFO[0m:     127.0.0.1:64113 - "[1mGET /v1/models HTTP/1.1[0m" [32m200 OK[0m
2025-04-11 21:14:51 | ERROR | stderr | [32mINFO[0m:     Shutting down
2025-04-11 21:14:51 | ERROR | stderr | [32mINFO[0m:     Waiting for application shutdown.
2025-04-11 21:14:51 | ERROR | stderr | [32mINFO[0m:     Application shutdown complete.
2025-04-11 21:14:51 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m18108[0m]
